# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pigil < Formula
  desc "Pigil - Homegrown Proces Vigilance System"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DarthBenro008/pigil/releases/download/v0.1.0/pigil_0.1.0_Darwin_arm64.tar.gz"
      sha256 "568e38ae44314a5fcc3a109063d7801847bc64e9e8831f51f398355483045db0"

      def install
        bin.install "pigil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DarthBenro008/pigil/releases/download/v0.1.0/pigil_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "09d5c356c3852687072d841baf910bfaee93f0142d230667089748d1902510c7"

      def install
        bin.install "pigil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DarthBenro008/pigil/releases/download/v0.1.0/pigil_0.1.0_Linux_arm64.tar.gz"
      sha256 "a410c5446dadcded6b8997b606fe7146ff4cceec40f9bf7f448068ad4bfec929"

      def install
        bin.install "pigil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DarthBenro008/pigil/releases/download/v0.1.0/pigil_0.1.0_Linux_x86_64.tar.gz"
      sha256 "37e8d288e246a60fc455c854ce4ff5fa7e2724793709969a5e37b57560e54593"

      def install
        bin.install "pigil"
      end
    end
  end
end
