# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pigil < Formula
  desc "Pigil - Homegrown Proces Vigilance System"
  homepage ""
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DarthBenro008/pigil/releases/download/0.1.5/pigil_0.1.5_Darwin_arm64.tar.gz"
      sha256 "452edc126ebbb0506f8c713394cac24012e7fe8971552ebc1c84055011fb02eb"

      def install
        bin.install "pigil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DarthBenro008/pigil/releases/download/0.1.5/pigil_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "e6eeceba72eb0af1194e327c9f12eeeb58300550bda1de8684530c8fa1672fef"

      def install
        bin.install "pigil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DarthBenro008/pigil/releases/download/0.1.5/pigil_0.1.5_Linux_arm64.tar.gz"
      sha256 "c350f56dbc12108809c7b0cbbf8eac82bc8fb1c200a982eddfb74afdb5d68988"

      def install
        bin.install "pigil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DarthBenro008/pigil/releases/download/0.1.5/pigil_0.1.5_Linux_x86_64.tar.gz"
      sha256 "6098d41cdd748afb37ba6ad3627329dec52d382904b8e73856449cb50aaee554"

      def install
        bin.install "pigil"
      end
    end
  end
end
